import type { MedicalDocument } from "@medvault/shared";

export const mockDocuments: MedicalDocument[] = [
  {
    id: "doc-demo-1",
    ownerId: "demo-user",
    profileId: "demo-profile",
    timelineEventId: "mock-2",
    title: "CBC and lipid panel",
    category: "lab_report",
    description: "Routine annual bloodwork with LDL flagged for lifestyle review.",
    originalFileName: "cbc-lipid-panel-may-2026.pdf",
    mimeType: "application/pdf",
    sizeBytes: 1_420_288,
    checksumSha256: "demo-checksum-cbc-lipid-panel",
    storageProvider: "local",
    storageKey: "demo/labs/cbc-lipid-panel-may-2026.pdf",
    tags: ["lab", "bloodwork", "annual"],
    uploadedAt: "2026-05-16T11:25:00.000Z",
    createdAt: "2026-05-16T11:25:00.000Z",
    updatedAt: "2026-05-16T11:25:00.000Z"
  },
  {
    id: "doc-demo-2",
    ownerId: "demo-user",
    profileId: "demo-profile",
    title: "Clinic prescription",
    category: "prescription",
    description: "Prescription note for Metformin 500mg twice daily.",
    originalFileName: "clinic-prescription-metformin.png",
    mimeType: "image/png",
    sizeBytes: 682_112,
    checksumSha256: "demo-checksum-metformin-prescription",
    storageProvider: "local",
    storageKey: "demo/prescriptions/clinic-prescription-metformin.png",
    tags: ["prescription", "diabetes"],
    uploadedAt: "2026-05-14T08:12:00.000Z",
    createdAt: "2026-05-14T08:12:00.000Z",
    updatedAt: "2026-05-14T08:12:00.000Z"
  },
  {
    id: "doc-demo-3",
    ownerId: "demo-user",
    profileId: "demo-profile",
    title: "Primary care visit note",
    category: "doctor_note",
    description: "Doctor notes from annual checkup and follow-up recommendations.",
    originalFileName: "primary-care-visit-note.pdf",
    mimeType: "application/pdf",
    sizeBytes: 928_768,
    checksumSha256: "demo-checksum-primary-care-note",
    storageProvider: "local",
    storageKey: "demo/notes/primary-care-visit-note.pdf",
    tags: ["visit", "primary-care"],
    uploadedAt: "2026-05-17T09:45:00.000Z",
    createdAt: "2026-05-17T09:45:00.000Z",
    updatedAt: "2026-05-17T09:45:00.000Z"
  },
  {
    id: "doc-demo-4",
    ownerId: "demo-user",
    profileId: "demo-profile",
    title: "Vaccination record",
    category: "vaccination",
    description: "Immunization summary for travel and routine care.",
    originalFileName: "vaccination-record.pdf",
    mimeType: "application/pdf",
    sizeBytes: 512_340,
    checksumSha256: "demo-checksum-vaccination-record",
    storageProvider: "local",
    storageKey: "demo/vaccination/vaccination-record.pdf",
    tags: ["vaccination", "travel"],
    uploadedAt: "2026-04-28T13:10:00.000Z",
    createdAt: "2026-04-28T13:10:00.000Z",
    updatedAt: "2026-04-28T13:10:00.000Z"
  }
];
